//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("OficinaModel", "FK_Veiculo_Cor", "Cor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Impacta.Infra.Repositorios.SqlServer.Ef.Designer.Cor), "Veiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Impacta.Infra.Repositorios.SqlServer.Ef.Designer.Veiculo), true)]
[assembly: EdmRelationshipAttribute("OficinaModel", "FK_Veiculo_Modelo", "Modelo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Impacta.Infra.Repositorios.SqlServer.Ef.Designer.Modelo), "Veiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Impacta.Infra.Repositorios.SqlServer.Ef.Designer.Veiculo), true)]
[assembly: EdmRelationshipAttribute("OficinaModel", "FK_Servico_TipoServico", "TipoServico", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Impacta.Infra.Repositorios.SqlServer.Ef.Designer.TipoServico), "Servico", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Impacta.Infra.Repositorios.SqlServer.Ef.Designer.Servico), true)]
[assembly: EdmRelationshipAttribute("OficinaModel", "FK_Servico_Veiculo", "Veiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Impacta.Infra.Repositorios.SqlServer.Ef.Designer.Veiculo), "Servico", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Impacta.Infra.Repositorios.SqlServer.Ef.Designer.Servico), true)]
[assembly: EdmRelationshipAttribute("OficinaModel", "ClienteVeiculo", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Impacta.Infra.Repositorios.SqlServer.Ef.Designer.Cliente), "Veiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Impacta.Infra.Repositorios.SqlServer.Ef.Designer.Veiculo))]

#endregion

namespace Impacta.Infra.Repositorios.SqlServer.Ef.Designer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OficinaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OficinaEntities object using the connection string found in the 'OficinaEntities' section of the application configuration file.
        /// </summary>
        public OficinaEntities() : base("name=OficinaEntities", "OficinaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OficinaEntities object.
        /// </summary>
        public OficinaEntities(string connectionString) : base(connectionString, "OficinaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OficinaEntities object.
        /// </summary>
        public OficinaEntities(EntityConnection connection) : base(connection, "OficinaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cor> Cor
        {
            get
            {
                if ((_Cor == null))
                {
                    _Cor = base.CreateObjectSet<Cor>("Cor");
                }
                return _Cor;
            }
        }
        private ObjectSet<Cor> _Cor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Modelo> Modelo
        {
            get
            {
                if ((_Modelo == null))
                {
                    _Modelo = base.CreateObjectSet<Modelo>("Modelo");
                }
                return _Modelo;
            }
        }
        private ObjectSet<Modelo> _Modelo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Servico> Servico
        {
            get
            {
                if ((_Servico == null))
                {
                    _Servico = base.CreateObjectSet<Servico>("Servico");
                }
                return _Servico;
            }
        }
        private ObjectSet<Servico> _Servico;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoServico> TipoServico
        {
            get
            {
                if ((_TipoServico == null))
                {
                    _TipoServico = base.CreateObjectSet<TipoServico>("TipoServico");
                }
                return _TipoServico;
            }
        }
        private ObjectSet<TipoServico> _TipoServico;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Veiculo> Veiculo
        {
            get
            {
                if ((_Veiculo == null))
                {
                    _Veiculo = base.CreateObjectSet<Veiculo>("Veiculo");
                }
                return _Veiculo;
            }
        }
        private ObjectSet<Veiculo> _Veiculo;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCor(Cor cor)
        {
            base.AddObject("Cor", cor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modelo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModelo(Modelo modelo)
        {
            base.AddObject("Modelo", modelo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Servico EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToServico(Servico servico)
        {
            base.AddObject("Servico", servico);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoServico EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoServico(TipoServico tipoServico)
        {
            base.AddObject("TipoServico", tipoServico);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Veiculo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVeiculo(Veiculo veiculo)
        {
            base.AddObject("Veiculo", veiculo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OficinaModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        public static Cliente CreateCliente(global::System.Int32 id, global::System.String nome, global::System.DateTime dataNascimento, global::System.Int32 tipo)
        {
            Cliente cliente = new Cliente();
            cliente.Id = id;
            cliente.Nome = nome;
            cliente.DataNascimento = dataNascimento;
            cliente.Tipo = tipo;
            return cliente;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.DateTime _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.DateTime value);
        partial void OnDataNascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.Int32 _Tipo;
        partial void OnTipoChanging(global::System.Int32 value);
        partial void OnTipoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OficinaModel", "ClienteVeiculo", "Veiculo")]
        public EntityCollection<Veiculo> Veiculos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Veiculo>("OficinaModel.ClienteVeiculo", "Veiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Veiculo>("OficinaModel.ClienteVeiculo", "Veiculo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OficinaModel", Name="Cor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cor object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Cor CreateCor(global::System.Int32 id, global::System.String descricao)
        {
            Cor cor = new Cor();
            cor.Id = id;
            cor.Descricao = descricao;
            return cor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OficinaModel", Name="Modelo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Modelo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Modelo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Modelo CreateModelo(global::System.Int32 id, global::System.String descricao)
        {
            Modelo modelo = new Modelo();
            modelo.Id = id;
            modelo.Descricao = descricao;
            return modelo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OficinaModel", Name="Servico")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Servico : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Servico object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="veiculo_Id">Initial value of the Veiculo_Id property.</param>
        /// <param name="tipoServico_Id">Initial value of the TipoServico_Id property.</param>
        public static Servico CreateServico(global::System.Int32 id, global::System.Int32 veiculo_Id, global::System.Int32 tipoServico_Id)
        {
            Servico servico = new Servico();
            servico.Id = id;
            servico.Veiculo_Id = veiculo_Id;
            servico.TipoServico_Id = tipoServico_Id;
            return servico;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Veiculo_Id
        {
            get
            {
                return _Veiculo_Id;
            }
            set
            {
                OnVeiculo_IdChanging(value);
                ReportPropertyChanging("Veiculo_Id");
                _Veiculo_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Veiculo_Id");
                OnVeiculo_IdChanged();
            }
        }
        private global::System.Int32 _Veiculo_Id;
        partial void OnVeiculo_IdChanging(global::System.Int32 value);
        partial void OnVeiculo_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TipoServico_Id
        {
            get
            {
                return _TipoServico_Id;
            }
            set
            {
                OnTipoServico_IdChanging(value);
                ReportPropertyChanging("TipoServico_Id");
                _TipoServico_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoServico_Id");
                OnTipoServico_IdChanged();
            }
        }
        private global::System.Int32 _TipoServico_Id;
        partial void OnTipoServico_IdChanging(global::System.Int32 value);
        partial void OnTipoServico_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInicio
        {
            get
            {
                return _DataInicio;
            }
            set
            {
                OnDataInicioChanging(value);
                ReportPropertyChanging("DataInicio");
                _DataInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInicio");
                OnDataInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInicio;
        partial void OnDataInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataFim
        {
            get
            {
                return _DataFim;
            }
            set
            {
                OnDataFimChanging(value);
                ReportPropertyChanging("DataFim");
                _DataFim = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataFim");
                OnDataFimChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataFim;
        partial void OnDataFimChanging(Nullable<global::System.DateTime> value);
        partial void OnDataFimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private Nullable<global::System.Decimal> _Valor;
        partial void OnValorChanging(Nullable<global::System.Decimal> value);
        partial void OnValorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OficinaModel", "FK_Servico_TipoServico", "TipoServico")]
        public TipoServico TipoServico
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoServico>("OficinaModel.FK_Servico_TipoServico", "TipoServico").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoServico>("OficinaModel.FK_Servico_TipoServico", "TipoServico").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoServico> TipoServicoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoServico>("OficinaModel.FK_Servico_TipoServico", "TipoServico");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoServico>("OficinaModel.FK_Servico_TipoServico", "TipoServico", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OficinaModel", "FK_Servico_Veiculo", "Veiculo")]
        public Veiculo Veiculo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Veiculo>("OficinaModel.FK_Servico_Veiculo", "Veiculo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Veiculo>("OficinaModel.FK_Servico_Veiculo", "Veiculo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Veiculo> VeiculoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Veiculo>("OficinaModel.FK_Servico_Veiculo", "Veiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Veiculo>("OficinaModel.FK_Servico_Veiculo", "Veiculo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OficinaModel", Name="TipoServico")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoServico : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoServico object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static TipoServico CreateTipoServico(global::System.Int32 id, global::System.String descricao)
        {
            TipoServico tipoServico = new TipoServico();
            tipoServico.Id = id;
            tipoServico.Descricao = descricao;
            return tipoServico;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OficinaModel", "FK_Servico_TipoServico", "Servico")]
        public EntityCollection<Servico> Servico
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Servico>("OficinaModel.FK_Servico_TipoServico", "Servico");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Servico>("OficinaModel.FK_Servico_TipoServico", "Servico", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OficinaModel", Name="Veiculo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Veiculo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Veiculo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="modelo_Id">Initial value of the Modelo_Id property.</param>
        /// <param name="cor_Id">Initial value of the Cor_Id property.</param>
        /// <param name="placa">Initial value of the Placa property.</param>
        /// <param name="anoFabricacao">Initial value of the AnoFabricacao property.</param>
        /// <param name="anoModelo">Initial value of the AnoModelo property.</param>
        public static Veiculo CreateVeiculo(global::System.Int32 id, global::System.Int32 modelo_Id, global::System.Int32 cor_Id, global::System.String placa, global::System.Int32 anoFabricacao, global::System.Int32 anoModelo)
        {
            Veiculo veiculo = new Veiculo();
            veiculo.Id = id;
            veiculo.Modelo_Id = modelo_Id;
            veiculo.Cor_Id = cor_Id;
            veiculo.Placa = placa;
            veiculo.AnoFabricacao = anoFabricacao;
            veiculo.AnoModelo = anoModelo;
            return veiculo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Modelo_Id
        {
            get
            {
                return _Modelo_Id;
            }
            set
            {
                OnModelo_IdChanging(value);
                ReportPropertyChanging("Modelo_Id");
                _Modelo_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modelo_Id");
                OnModelo_IdChanged();
            }
        }
        private global::System.Int32 _Modelo_Id;
        partial void OnModelo_IdChanging(global::System.Int32 value);
        partial void OnModelo_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cor_Id
        {
            get
            {
                return _Cor_Id;
            }
            set
            {
                OnCor_IdChanging(value);
                ReportPropertyChanging("Cor_Id");
                _Cor_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cor_Id");
                OnCor_IdChanged();
            }
        }
        private global::System.Int32 _Cor_Id;
        partial void OnCor_IdChanging(global::System.Int32 value);
        partial void OnCor_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Placa
        {
            get
            {
                return _Placa;
            }
            set
            {
                OnPlacaChanging(value);
                ReportPropertyChanging("Placa");
                _Placa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Placa");
                OnPlacaChanged();
            }
        }
        private global::System.String _Placa;
        partial void OnPlacaChanging(global::System.String value);
        partial void OnPlacaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AnoFabricacao
        {
            get
            {
                return _AnoFabricacao;
            }
            set
            {
                OnAnoFabricacaoChanging(value);
                ReportPropertyChanging("AnoFabricacao");
                _AnoFabricacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnoFabricacao");
                OnAnoFabricacaoChanged();
            }
        }
        private global::System.Int32 _AnoFabricacao;
        partial void OnAnoFabricacaoChanging(global::System.Int32 value);
        partial void OnAnoFabricacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AnoModelo
        {
            get
            {
                return _AnoModelo;
            }
            set
            {
                OnAnoModeloChanging(value);
                ReportPropertyChanging("AnoModelo");
                _AnoModelo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnoModelo");
                OnAnoModeloChanged();
            }
        }
        private global::System.Int32 _AnoModelo;
        partial void OnAnoModeloChanging(global::System.Int32 value);
        partial void OnAnoModeloChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OficinaModel", "FK_Veiculo_Cor", "Cor")]
        public Cor Cor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cor>("OficinaModel.FK_Veiculo_Cor", "Cor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cor>("OficinaModel.FK_Veiculo_Cor", "Cor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cor> CorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cor>("OficinaModel.FK_Veiculo_Cor", "Cor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cor>("OficinaModel.FK_Veiculo_Cor", "Cor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OficinaModel", "FK_Veiculo_Modelo", "Modelo")]
        public Modelo Modelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("OficinaModel.FK_Veiculo_Modelo", "Modelo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("OficinaModel.FK_Veiculo_Modelo", "Modelo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Modelo> ModeloReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("OficinaModel.FK_Veiculo_Modelo", "Modelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Modelo>("OficinaModel.FK_Veiculo_Modelo", "Modelo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OficinaModel", "FK_Servico_Veiculo", "Servico")]
        public EntityCollection<Servico> Servicos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Servico>("OficinaModel.FK_Servico_Veiculo", "Servico");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Servico>("OficinaModel.FK_Servico_Veiculo", "Servico", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OficinaModel", "ClienteVeiculo", "Cliente")]
        public EntityCollection<Cliente> Clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cliente>("OficinaModel.ClienteVeiculo", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cliente>("OficinaModel.ClienteVeiculo", "Cliente", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
