//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impacta.Infra.Repositorios.SqlServer.Ef.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public Veiculo()
        {
            this.Servicos = new HashSet<Servico>();
            this.Clientes = new HashSet<Cliente>();
        }
    
        public int Id { get; set; }
        public int Modelo_Id { get; set; }
        public int Cor_Id { get; set; }
        public string Placa { get; set; }
        public int AnoFabricacao { get; set; }
        public int AnoModelo { get; set; }
    
        public virtual Cor Cor { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual ICollection<Servico> Servicos { get; set; }
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}
