//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impacta.Repositorios.Ef.Designer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OficinaEntities : DbContext
    {
        public OficinaEntities()
            : base("name=OficinaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Cor> Cor { get; set; }
        public DbSet<Modelo> Modelo { get; set; }
        public DbSet<Servico> Servico { get; set; }
        public DbSet<TipoServico> TipoServico { get; set; }
        public DbSet<Veiculo> Veiculo { get; set; }
        public DbSet<Montadora> Montadora { get; set; }
    }
}
