//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impacta.Repositorios.Ef.Designer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PedidosEntities : DbContext
    {
        public PedidosEntities()
            : base("name=PedidosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cidade> Cidades { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Estado> Estadoes { get; set; }
        public DbSet<ItensPedido> ItensPedidoes { get; set; }
        public DbSet<Pedido> Pedidoes { get; set; }
        public DbSet<Pessoa> Pessoas { get; set; }
        public DbSet<PessoaDocumento> PessoaDocumentos { get; set; }
        public DbSet<PessoaEndereco> PessoaEnderecos { get; set; }
        public DbSet<Produto> Produtoes { get; set; }
        public DbSet<TipoProduto> TipoProdutoes { get; set; }
        public DbSet<Vendedor> Vendedors { get; set; }
    }
}
