//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impacta.Repositorios.Ef.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.ItensPedidoes = new HashSet<ItensPedido>();
        }
    
        public int Id { get; set; }
        public System.DateTime DataEmissao { get; set; }
        public int Situacao { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<ItensPedido> ItensPedidoes { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
