//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impacta.Repositorios.Ef.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Cliente = new HashSet<Cliente>();
            this.PessoaDocumentos = new HashSet<PessoaDocumentos>();
            this.PessoaEnderecos = new HashSet<PessoaEnderecos>();
            this.Vendedor = new HashSet<Vendedor>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public System.DateTime DataNascimento { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<PessoaDocumentos> PessoaDocumentos { get; set; }
        public virtual ICollection<PessoaEnderecos> PessoaEnderecos { get; set; }
        public virtual ICollection<Vendedor> Vendedor { get; set; }
    }
}
