//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impacta.Repositorios.Ef.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Clientes = new HashSet<Cliente>();
            this.PessoaDocumentos = new HashSet<PessoaDocumento>();
            this.PessoaEnderecos = new HashSet<PessoaEndereco>();
            this.Vendedors = new HashSet<Vendedor>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<PessoaDocumento> PessoaDocumentos { get; set; }
        public virtual ICollection<PessoaEndereco> PessoaEnderecos { get; set; }
        public virtual ICollection<Vendedor> Vendedors { get; set; }
    }
}
